export const AUTH_USER = 'auth_user'
export const UNAUTH_USER = 'unauth_user'
export const AUTH_ERROR = 'auth_error'
export const AUTH_DETAIL = 'auth_detail'

export const FETCH_MOVIE_SUGGESTIONS = 'fetch_movie_suggestions'
export const RESET_MOVIE_SUGGESTIONS = 'reset_movie_suggestions'
export const SET_MOVIE_ID = 'set_movie_id'
export const FETCH_ACTOR_SUGGESTIONS = 'fetch_actor_suggestions'

export const FETCH_TMDB_DETAILS = 'fetch_tmdb_details'
export const FETCH_TMDB_DETAILS_ERRORS = 'fetch_tmdb_details_error'

export const CREATE_REMAKE = 'create_remake'
export const FETCH_REMAKES = 'fetch_remakes'
export const FETCH_REMAKE = 'fetch_remake'
export const FETCH_REMAKE_ERROR = 'fetch_remake_error'
export const DELETE_REMAKE = 'delete_remake'
export const CLOSE_REMAKE = 'close_remake'
export const RESET_REMAKE = 'reset_remake'
